name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust (stable)
        run: rustup show active-toolchain
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose

  miri:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust (nightly) and Miri
        run: |
          rustup override set nightly  
          rustup component add miri
      - name: Run tests with Miri
        run: cargo miri test
